//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnCNet.LauncherStub.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CnCNet.LauncherStub.LocalizationResources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch DirectX11 version.
        /// </summary>
        public static string Button_LaunchDX {
            get {
                return ResourceManager.GetString("Button_LaunchDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch XNA version.
        /// </summary>
        public static string Button_LaunchXNA {
            get {
                return ResourceManager.GetString("Button_LaunchXNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link.
        /// </summary>
        public static string Button_OpenLink {
            get {
                return ResourceManager.GetString("Button_OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link (All buttons here won&apos;t work).
        /// </summary>
        public static string Button_OpenLink_AllButtonsWonTWork {
            get {
                return ResourceManager.GetString("Button_OpenLink_AllButtonsWonTWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Launcher Error.
        /// </summary>
        public static string ClientLauncher_ErrorTitle {
            get {
                return ResourceManager.GetString("ClientLauncher_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Launcher Warning.
        /// </summary>
        public static string ClientLauncher_WarningTitle {
            get {
                return ResourceManager.GetString("ClientLauncher_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show incompatible GPU dialog.
        /// </summary>
        public static string Command_ShowIncompatibleGPU {
            get {
                return ResourceManager.GetString("Command_ShowIncompatibleGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show missing component dialog.
        /// </summary>
        public static string Command_ShowMissingComponent {
            get {
                return ResourceManager.GetString("Command_ShowMissingComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component name here.
        /// </summary>
        public static string Command_ShowMissingComponent_ComponentNamePlaceholder {
            get {
                return ResourceManager.GetString("Command_ShowMissingComponent_ComponentNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw an exception.
        /// </summary>
        public static string Command_ThrowException {
            get {
                return ResourceManager.GetString("Command_ThrowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message here.
        /// </summary>
        public static string Command_ThrowException_Message {
            get {
                return ResourceManager.GetString("Command_ThrowException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the buttons below to run dialog test..
        /// </summary>
        public static string DialogTest_Message {
            get {
                return ResourceManager.GetString("DialogTest_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the buttons below to run dialog test. Note: if you did not expect this, please make sure you have built the executable in Release configuration..
        /// </summary>
        public static string DialogTest_Message_Debug {
            get {
                return ResourceManager.GetString("DialogTest_Message_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Launcher Dialog Test.
        /// </summary>
        public static string DialogTest_Title {
            get {
                return ResourceManager.GetString("DialogTest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client has detected an incompatibility between your graphics card and both the DirectX11 and OpenGL versions of the CnCNet client..
        /// </summary>
        public static string IncompatibleGPU_Message_Line1 {
            get {
                return ResourceManager.GetString("IncompatibleGPU_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XNA version of the client could still work on your system, but it needs Microsoft XNA Framework 4.0 Refresh to be installed..
        /// </summary>
        public static string IncompatibleGPU_Message_Line2 {
            get {
                return ResourceManager.GetString("IncompatibleGPU_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the installer from the following link:.
        /// </summary>
        public static string IncompatibleGPU_Message_Line3 {
            get {
                return ResourceManager.GetString("IncompatibleGPU_Message_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively, you can retry launching the DirectX11 version of the client..
        /// </summary>
        public static string IncompatibleGPU_Message_Line4 {
            get {
                return ResourceManager.GetString("IncompatibleGPU_Message_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologize for the inconvenience..
        /// </summary>
        public static string IncompatibleGPU_Message_Line5 {
            get {
                return ResourceManager.GetString("IncompatibleGPU_Message_Line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Card Incompatibility Detected.
        /// </summary>
        public static string IncompatibleGPU_Title {
            get {
                return ResourceManager.GetString("IncompatibleGPU_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main client executable ({0}) not found!.
        /// </summary>
        public static string MainClientExecutable_NotFound {
            get {
                return ResourceManager.GetString("MainClientExecutable_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main client library ({0}) not found!.
        /// </summary>
        public static string MainClientLibrary_NotFound {
            get {
                return ResourceManager.GetString("MainClientLibrary_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component {0} is missing..
        /// </summary>
        public static string MissingComponent_Message_Line1 {
            get {
                return ResourceManager.GetString("MissingComponent_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the installer from the following link:.
        /// </summary>
        public static string MissingComponent_Message_Line2 {
            get {
                return ResourceManager.GetString("MissingComponent_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Missing.
        /// </summary>
        public static string MissingComponent_Title {
            get {
                return ResourceManager.GetString("MissingComponent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when the launcher tried to unblock files. Re-running the launcher with administrator privileges might help..
        /// </summary>
        public static string RemoveZoneIdentifer_ErrorMessage {
            get {
                return ResourceManager.GetString("RemoveZoneIdentifer_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove Zone.Identifier from the following files:.
        /// </summary>
        public static string RemoveZoneIdentifer_FailedList {
            get {
                return ResourceManager.GetString("RemoveZoneIdentifer_FailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch the main client. It could be blocked by Windows SmartScreen..
        /// </summary>
        public static string SmartScreen_Blocked_Line1 {
            get {
                return ResourceManager.GetString("SmartScreen_Blocked_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try to launch the following file manually:.
        /// </summary>
        public static string SmartScreen_Blocked_Line2 {
            get {
                return ResourceManager.GetString("SmartScreen_Blocked_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the client still doesn&apos;t run, please contact the mod&apos;s authors for support..
        /// </summary>
        public static string SmartScreen_Blocked_Line3 {
            get {
                return ResourceManager.GetString("SmartScreen_Blocked_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client requires at least .NET Framework 4.8 to run, but it is not supported on your operating system..
        /// </summary>
        public static string UnsupportedOS_Message_Line1 {
            get {
                return ResourceManager.GetString("UnsupportedOS_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider upgrading to a newer version of Windows..
        /// </summary>
        public static string UnsupportedOS_Message_Line2 {
            get {
                return ResourceManager.GetString("UnsupportedOS_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Operating System.
        /// </summary>
        public static string UnsupportedOS_Title {
            get {
                return ResourceManager.GetString("UnsupportedOS_Title", resourceCulture);
            }
        }
    }
}
